// src/app/pages/stages/stages.component.ts
import { Component, inject, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { TrackerState, Student, STAGES } from '../../state';
import { ToastService } from '../../shared/services/toast.service';
import { ModalService } from '../../shared/services/modal.service';
import { CelebrationService } from '../../shared/services/celebration.service';
import { ApiService } from '../../api.service';
import { getAvatarEmoji } from '../../shared/constants/avatars';

import { AppIconComponent } from '../../shared/components/app-icon/app-icon.component';

@Component({
  selector: 'app-stages',
  imports: [CommonModule, ReactiveFormsModule, AppIconComponent],
  template: `
    <div class="space-y-6">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <!-- Admin Tools Column -->
        <div class="space-y-4 lg:col-span-1">
          <!-- Stats Card -->
          <div class="panel p-5">
            <h3 class="panel-title">
              <span class="panel-title-icon">dashboard</span>
              إحصائيات الإدارة
            </h3>
            <div class="space-y-3">
              <div class="flex justify-between items-center p-3 bg-[var(--color-canvas)] border border-[var(--color-border-light)]">
                <span class="text-xs font-medium text-[var(--color-text-secondary)]">إجمالي الطلاب</span>
                <span class="badge-number-sm">{{ state.students().length }}</span>
              </div>
              <div class="flex justify-between items-center p-3 bg-[var(--color-canvas)] border border-[var(--color-border-light)]">
                <span class="text-xs font-medium text-[var(--color-text-secondary)]">مجموع النقاط</span>
                <span class="badge-number-sm">{{ totalXP }} XP</span>
              </div>
              <div class="flex justify-between items-center p-3 bg-[var(--color-canvas)] border border-[var(--color-border-light)]">
                <span class="text-xs font-medium text-[var(--color-text-secondary)]">أعلى طالب</span>
                <span class="badge-number-sm">{{ topStudentName }}</span>
              </div>
            </div>
          </div>

          <!-- Batch Actions -->
          <div class="panel p-5">
            <h3 class="panel-title">
              <span class="panel-title-icon">build</span>
              أدوات الإدارة
            </h3>
            <div class="space-y-2">
              <button (click)="showAddStudent()"
                class="btn btn-primary btn-md w-full">
                <app-icon name="person_add" [size]="18"></app-icon>
                إضافة طالب جديد
              </button>
              <p class="text-[11px] text-[var(--color-text-tertiary)] leading-relaxed mt-2 p-2 bg-[var(--color-amber-light)] border border-[var(--color-amber)]/30">
                <span class="font-semibold">ختم 40:</span> يوسم جميع الأحاديث الأربعين كمحفوظة دفعة واحدة.
                <br><span class="font-semibold">تصفير:</span> يعيد تعيين سجل حفظ الطالب بالكامل.
              </p>
            </div>
          </div>
        </div>

        <!-- Students Directory -->
        <div class="space-y-4 lg:col-span-2">
          <div class="panel p-5">
            <div class="flex items-center justify-between mb-5 pb-4 border-b border-[var(--color-border-light)]">
              <h3 class="font-tajawal text-lg font-bold text-[var(--color-text-primary)] flex items-center gap-2">
                <app-icon name="people" [size]="18"></app-icon>
                الطلاب النشطون
              </h3>
              <span class="tag tag-primary">
                {{ state.students().length }} طلاب
              </span>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              @for (student of state.students(); track student.id) {
              @let stage = state.getStudentStage(student);
              <div class="panel p-4 flex flex-col justify-between bg-[var(--color-canvas)]">
                <div>
                  <div class="flex items-start justify-between gap-2 mb-3">
                    <div class="flex items-center gap-2.5">
                      <div class="w-9 h-9 bg-[var(--color-surface)] border border-[var(--color-border)] flex items-center justify-center text-lg shrink-0">
                        {{ getAvatarEmoji(student.avatar) }}
                      </div>
                      <div>
                        <h4 class="font-bold text-sm text-[var(--color-text-primary)]">{{ student.name }}</h4>
                        <p class="text-[11px] text-[var(--color-text-tertiary)] font-medium">{{ student.age ? student.age + ' سنة' : 'غير محدد' }}</p>
                      </div>
                    </div>
                    <span class="tag tag-primary">{{ stage.name }}</span>
                  </div>

                  <div class="my-3">
                    <div class="flex justify-between text-[11px] font-semibold text-[var(--color-text-secondary)] mb-1">
                      <span>الأحاديث:</span>
                      <span class="text-[var(--color-primary-dark)]">{{ student.memorizedHadithNumbers.length }} / {{ state.hadiths().length }}</span>
                    </div>
                    <div class="progress-bar">
                      <div class="progress-fill" [style.width.%]="(student.memorizedHadithNumbers.length / (state.hadiths().length || 1)) * 100"></div>
                    </div>
                  </div>

                  @if (student.notes) {
                  <p class="text-[11px] text-[var(--color-text-tertiary)] bg-[var(--color-surface)] p-2 border border-[var(--color-border-light)] italic mb-3 max-h-12 overflow-y-auto">
                    "{{ student.notes }}"
                  </p>
                  }
                </div>

                <div class="flex items-center justify-between pt-2.5 border-t border-[var(--color-border-light)]">
                  <div class="flex gap-1.5">
                    <button (click)="openEditStudent(student)" class="btn btn-ghost btn-icon" title="تعديل" aria-label="تعديل الطالب">
                      <app-icon name="edit" [size]="18"></app-icon>
                    </button>
                    <button (click)="onDeleteStudent(student.id, student.name)" class="btn btn-ghost btn-icon hover:text-[var(--color-rose)] hover:bg-[var(--color-rose-light)]" title="حذف" aria-label="حذف الطالب">
                      <app-icon name="delete" [size]="18"></app-icon>
                    </button>
                  </div>
                  <div class="flex gap-1.5">
                    <button (click)="cheatUnlockAll(student.id)" class="btn btn-sm bg-[var(--color-amber-light)] text-[var(--color-text-primary)] border border-[var(--color-amber)] hover:bg-[var(--color-amber)]" title="ختم الأربعين">
                      ختم 40
                    </button>
                    <button (click)="resetStudentProgress(student.id)" class="btn btn-sm border border-[var(--color-border)] bg-[var(--color-canvas)] text-[var(--color-text-tertiary)] hover:bg-[var(--color-border)]" title="تصفير">
                      تصفير
                    </button>
                  </div>
                </div>
              </div>
              } @empty {
              <div class="col-span-2 empty-state">
                <span class="empty-state-icon">person_off</span>
                <p class="empty-state-text">لا يوجد طلاب نشطين</p>
                <button (click)="showAddStudent()" class="btn btn-primary btn-md mt-4">سجل أول طالب</button>
              </div>
              }
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class StagesComponent {
  state = inject(TrackerState);
  toast = inject(ToastService);
  modal = inject(ModalService);
  celebration = inject(CelebrationService);
  api = inject(ApiService);

  getAvatarEmoji = getAvatarEmoji;

  get totalXP(): number {
    return this.state.students().reduce((sum, s) => sum + s.xp, 0);
  }

  get topStudentName(): string {
    const students = this.state.students();
    if (students.length === 0) return '—';
    return students.reduce((a, b) => (a.xp > b.xp ? a : b)).name;
  }

  showAddStudent() {
    this.modal.showAddStudent.set(true);
  }

  openEditStudent(student: Student) {
    window.dispatchEvent(new CustomEvent('editStudent', { detail: student }));
    this.modal.showEditStudent.set(true);
  }

  onDeleteStudent(id: string, name: string) {
    this.modal.confirm(`هل أنت متأكد من حذف الطالب (${name})؟ سيتم مسح سجل الحفظ بالكامل.`, () => {
      this.state.deleteStudent(id);
      this.toast.show('تم حذف الطالب من السجل.');
      this.modal.confirmState.set(null);
    });
  }

  cheatUnlockAll(studentId: string) {
    const student = this.state.students().find((s) => s.id === studentId);
    if (!student) return;
    this.modal.confirm(`هل تريد وسم جميع الأحاديث الـ 40 كـ "محفوظة" للطالب (${student.name})؟`, () => {
      const updated = this.state.students().map((s) => {
        if (s.id === studentId) {
          const allNums = Array.from({ length: 40 }, (_, i) => i + 1);
          return { ...s, memorizedHadithNumbers: allNums, reviewHadithNumbers: [], xp: 4000 };
        }
        return s;
      });
      this.state.students.set(updated);
      const saved = updated.find((s) => s.id === studentId);
      if (saved) this.api.saveStudent(saved).catch(() => this.toast.show('فشل حفظ بيانات الطالب', 'error'));
      const updatedStudent = updated.find((s) => s.id === studentId)!;
      this.celebration.trigger(updatedStudent, STAGES[4]);
      this.toast.show(`هنيئاً! تم إتمام حفظ الأربعين لـ ${updatedStudent.name}!`);
      this.modal.confirmState.set(null);
    });
  }

  resetStudentProgress(studentId: string) {
    const student = this.state.students().find((s) => s.id === studentId);
    if (!student) return;
    this.modal.confirm(`هل تريد تصفير سجل حفظ الطالب (${student.name})؟`, () => {
      const updated = this.state.students().map((s) => {
        if (s.id === studentId) {
          return { ...s, memorizedHadithNumbers: [], reviewHadithNumbers: [], memorizedSurahNumbers: [], reviewSurahNumbers: [], memorizedSurahPages: [], memorizedEnglishUnits: [], reviewEnglishUnits: [], xp: 0 };
        }
        return s;
      });
      this.state.students.set(updated);
      const savedStudent = updated.find((s) => s.id === studentId);
      if (savedStudent) this.api.saveStudent(savedStudent).catch(() => this.toast.show('فشل حفظ بيانات الطالب', 'error'));
      this.toast.show('تم تصفير سجل الحفظ.');
      this.modal.confirmState.set(null);
    });
  }
}

// src/app/stages/page.tsx
"use client";

import { useState, useMemo } from "react";
import { useData, useUI } from "@/lib/tracker-context";
import AppIcon from "@/components/app-icon";
import { getAvatarEmoji } from "@/lib/constants";
import EditStudentModal from "@/components/modals/edit-student-modal";
import AddStudentModal from "@/components/modals/add-student-modal";
import type { Student } from "@/lib/types";

export default function StagesPage() {
  const { state, getStudentStage, deleteStudent, cheatUnlockAll, resetStudentProgress } = useData();
  const { confirm } = useUI();
  const [editStudent, setEditStudent] = useState<Student | null>(null);
  const [addStudentOpen, setAddStudentOpen] = useState(false);

  const stats = useMemo(() => {
    const list = state.students;
    if (list.length === 0) return { totalXP: 0, topStudentName: "" };
    const totalXP = list.reduce((sum, s) => sum + s.xp, 0);
    const top = list.reduce((a, b) => (a.xp > b.xp ? a : b));
    return { totalXP, topStudentName: top.xp > 0 ? top.name : "" };
  }, [state.students]);

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Admin tools sidebar */}
        <div className="space-y-4">
          <div className="panel p-5">
            <h3 className="panel-title mb-4">أدوات الإدارة</h3>
            <div className="text-2xl font-bold text-primary-dark mb-2">{state.students.length}</div>
            <p className="text-xs text-text-secondary mb-1">إجمالي XP: {stats.totalXP}</p>
            {stats.topStudentName && <p className="text-xs text-text-tertiary">الصدارة: {stats.topStudentName}</p>}
          </div>
          <button className="btn btn-primary btn-md w-full" onClick={() => setAddStudentOpen(true)}>
            <AppIcon name="person_add" size={16} /> إضافة طالب جديد
          </button>
        </div>

        {/* Student grid */}
        <div className="lg:col-span-3">
          <div className="flex items-center gap-2 mb-4">
            <AppIcon name="people" size={18} className="text-text-tertiary" />
            <h3 className="font-bold text-text-primary">الطلاب النشطون</h3>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
            {state.students.map((student) => {
              const stage = getStudentStage(student);
              const progress = Math.min(Math.round((student.xp / (stage.maxXP > 10000 ? stage.minXP : stage.maxXP)) * 100), 100);
              return (
                <div key={student.id} className="panel bg-canvas p-4">
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <span className="text-2xl">{getAvatarEmoji(student.avatar)}</span>
                      <div>
                        <p className="font-bold text-sm text-text-primary">{student.name}</p>
                        <p className="text-2xs text-text-tertiary">{student.age ? `${student.age} سنة` : ""}</p>
                      </div>
                    </div>
                    <div className="flex gap-1">
                      <button className="btn btn-icon btn-ghost" title="تعديل" onClick={() => setEditStudent(student)}><AppIcon name="edit" size={14} /></button>
                      <button className="btn btn-icon btn-ghost" title="حذف" onClick={() => confirm.ask("هل أنت متأكد من حذف الطالب؟", () => deleteStudent(student.id))}>
                        <AppIcon name="delete" size={14} />
                      </button>
                    </div>
                  </div>
                  <span className="tag tag-primary text-2xs mb-2">{stage.name}</span>
                  {student.notes && <p className="text-2xs text-text-tertiary mb-2 truncate">{student.notes}</p>}
                  <div className="mt-3">
                    <div className="flex justify-between text-2xs text-text-tertiary mb-1">
                      <span>{student.memorizedHadithNumbers.length}/{state.hadiths.length} حديث</span>
                      <span>{student.xp} XP</span>
                    </div>
                    <div className="progress-bar"><div className="progress-fill" style={{ width: `${progress}%` }} /></div>
                  </div>
                  {/* Admin actions */}
                  <div className="flex gap-2 mt-3 pt-3 border-t border-border-light">
                    <button
                      className="btn btn-outline btn-sm flex-1 text-green border-green"
                      onClick={() => confirm.ask("سيؤدي هذا إلى تعليم جميع الأحاديث كمحفوظة للطالب. متأكد؟", () => cheatUnlockAll(student.id))}
                    >
                      <AppIcon name="emoji_events" size={12} /> ختم 40
                    </button>
                    <button
                      className="btn btn-outline btn-sm flex-1 text-rose border-rose"
                      onClick={() => confirm.ask("سيؤدي هذا إلى تصفير تقدم الطالب بالكامل. متأكد؟", () => resetStudentProgress(student.id))}
                    >
                      <AppIcon name="restart_alt" size={12} /> تصفير
                    </button>
                  </div>
                </div>
              );
            })}
            {state.students.length === 0 && (
              <div className="col-span-full empty-state"><p className="empty-state-text">لا يوجد طلاب مسجلون</p></div>
            )}
          </div>
        </div>
      </div>

      <EditStudentModal student={editStudent} open={!!editStudent} onClose={() => setEditStudent(null)} />
      <AddStudentModal open={addStudentOpen} onClose={() => setAddStudentOpen(false)} />
    </div>
  );
}
