// src/app/shared/modals/edit-hadith-modal.component.ts
import { Component, inject, signal, OnInit, OnDestroy, HostListener } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { TrackerState } from '../../state';
import { Hadith } from '../../hadith-data';
import { ToastService } from '../services/toast.service';
import { ModalService } from '../services/modal.service';

@Component({
  selector: 'app-edit-hadith-modal',
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    @if (modal.showEditHadith()) {
    <div class="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="editHadithTitle" (click)="close()">
      <div class="modal-panel max-w-lg" (click)="$event.stopPropagation()">
        <div class="flex items-center justify-between mb-5 pb-4 border-b border-[var(--color-border-light)]">
          <h3 id="editHadithTitle" class="font-tajawal text-lg font-bold text-[var(--color-text-primary)] flex items-center gap-2">
            <span class="material-icons text-[var(--color-primary)]">edit_note</span>
            تعديل الحديث رقم {{ form.get('number')?.value }}
          </h3>
          <button (click)="modal.showEditHadith.set(false)" class="btn btn-ghost btn-icon" aria-label="إغلاق">
            <span class="material-icons text-sm">close</span>
          </button>
        </div>

        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4">
          <div>
            <label for="editHadithNumber" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">رقم الحديث *</label>
            <input id="editHadithNumber" type="number" formControlName="number" min="1"
              class="input-field" />
          </div>

          <div>
            <label for="editHadithText" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">نص الحديث *</label>
            <textarea id="editHadithText" formControlName="text" rows="3"
              class="input-field font-amiri text-lg text-center"></textarea>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div>
              <label for="editHadithCategory" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">القسم / الباب *</label>
              @if (showNewCategory()) {
              <div class="flex gap-2">
                <input id="editHadithCategory" type="text" formControlName="category" placeholder="اسم التصنيف الجديد"
                  class="input-field flex-1" />
                <button type="button" (click)="showNewCategory.set(false)"
                  class="btn btn-sm border border-[var(--color-border)] bg-[var(--color-surface)] hover:bg-[var(--color-canvas)] whitespace-nowrap">
                  اختر من القائمة
                </button>
              </div>
              } @else {
              <div class="flex gap-2">
                <select id="editHadithCategory" formControlName="category"
                  class="input-field flex-1 cursor-pointer">
                  @for (cat of uniqueCategories(); track cat) {
                  <option [value]="cat">{{ cat }}</option>
                  }
                </select>
                <button type="button" (click)="startNewCategory()"
                  class="btn btn-sm border border-[var(--color-border)] bg-[var(--color-surface)] hover:bg-[var(--color-canvas)] whitespace-nowrap">
                  جديد
                </button>
              </div>
              }
            </div>
            <div>
              <label for="editHadithReference" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">راوي الحديث *</label>
              <input id="editHadithReference" type="text" formControlName="reference" placeholder="مثال: عن أبي هريرة"
                class="input-field" />
            </div>
          </div>

          <div>
            <label for="editHadithExplanation" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">الشرح والتوجيه *</label>
            <textarea id="editHadithExplanation" formControlName="explanation" rows="3"
              class="input-field"></textarea>
          </div>

          <div class="flex items-center gap-3 pt-2">
            <button type="submit" [disabled]="form.invalid"
              class="btn btn-primary btn-md flex-1 disabled:opacity-50 disabled:cursor-not-allowed">
              <span class="material-icons text-sm">check</span>
              حفظ التعديلات
            </button>
            <button type="button" (click)="modal.showEditHadith.set(false)"
              class="btn btn-outline btn-md">
              إلغاء
            </button>
          </div>
        </form>
      </div>
    </div>
    }
  `,
})
export class EditHadithModalComponent implements OnInit, OnDestroy {
  state = inject(TrackerState);
  toast = inject(ToastService);
  modal = inject(ModalService);

  showNewCategory = signal(false);

  private listener = ((e: CustomEvent) => this.open(e.detail)) as EventListener;

  ngOnInit() {
    if (typeof window !== 'undefined') {
      window.addEventListener('editHadith', this.listener);
    }
  }

  ngOnDestroy() {
    if (typeof window !== 'undefined') {
      window.removeEventListener('editHadith', this.listener);
    }
  }

  selectedHadithForEdit = signal<Hadith | null>(null);

  form = new FormGroup({
    number: new FormControl<number>(0, { nonNullable: true, validators: [Validators.required] }),
    text: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.minLength(5)] }),
    reference: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    explanation: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    category: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
  });

  uniqueCategories() {
    const cats = new Set<string>();
    this.state.hadiths().forEach((h) => cats.add(h.category));
    return Array.from(cats);
  }

  open(hadith: Hadith) {
    this.selectedHadithForEdit.set(hadith);
    this.showNewCategory.set(false);
    this.form.setValue({
      number: hadith.number,
      text: hadith.text,
      reference: hadith.reference,
      explanation: hadith.explanation,
      category: hadith.category,
    });
    this.modal.showEditHadith.set(true);
  }

  startNewCategory() {
    this.showNewCategory.set(true);
    this.form.patchValue({ category: '' });
  }

  onSubmit() {
    if (this.form.invalid) return;
    const val = this.form.value;
    const success = this.state.updateHadith(
      this.selectedHadithForEdit()?.number ?? 0,
      val.number || 0,
      val.text || '',
      val.reference || '',
      val.explanation || '',
      val.category || '',
    );
    this.modal.showEditHadith.set(false);
    if (success) {
      this.toast.show('تم تحديث الحديث الشريف بنجاح!');
    } else {
      this.toast.show('فشل التحديث — ربما الرقم مستخدم مسبقاً.');
    }
  }

  close() {
    this.modal.showEditHadith.set(false);
  }

  @HostListener('document:keydown.escape')
  onEscape() {
    this.close();
  }
}

// src/components/modals/edit-hadith-modal.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { useData } from "@/lib/tracker-context";
import AppIcon from "@/components/app-icon";
import type { Hadith } from "@/lib/types";

interface Props {
  hadith: Hadith | null;
  open: boolean;
  onClose: () => void;
}

export default function EditHadithModal({ hadith, open, onClose }: Props) {
  const { state, updateHadith } = useData();
  const [number, setNumber] = useState<number>(0);
  const [text, setText] = useState("");
  const [reference, setReference] = useState("");
  const [explanation, setExplanation] = useState("");
  const [category, setCategory] = useState("");
  const [showNewCategory, setShowNewCategory] = useState(false);
  const [error, setError] = useState("");

  const categories = [...new Set(state.hadiths.map((h) => h.category).filter(Boolean))].sort();

  useEffect(() => {
    if (hadith) {
      setNumber(hadith.number); setText(hadith.text); setReference(hadith.reference);
      setExplanation(hadith.explanation); setCategory(hadith.category); setError("");
    }
  }, [hadith]);

  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    if (open) window.addEventListener("keydown", handleEsc);
    return () => window.removeEventListener("keydown", handleEsc);
  }, [open, onClose]);

  const submit = useCallback(async () => {
    if (!hadith) return;
    const ok = await updateHadith(hadith.number, number, text, reference, explanation, category);
    if (!ok) setError("رقم الحديث موجود مسبقاً");
    else onClose();
  }, [hadith, number, text, reference, explanation, category, updateHadith, onClose]);

  if (!open || !hadith) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center" role="dialog" aria-modal="true">
      <div className="absolute inset-0 bg-overlay" onClick={onClose} />
      <div className="relative modal-panel max-w-lg animate-fade-in">
        <div className="flex items-center justify-between mb-6">
          <h2 className="panel-title">
            <AppIcon name="edit_note" size={20} className="text-primary" />
            تعديل الحديث
          </h2>
          <button className="btn btn-icon btn-ghost" onClick={onClose}><AppIcon name="close" size={18} /></button>
        </div>

        {error && <p className="text-sm text-rose bg-rose-light p-2 mb-4">{error}</p>}

        <div className="space-y-4">
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">رقم الحديث</label>
            <input className="input-field" type="number" min={1} value={number || ""} onChange={(e) => setNumber(Number(e.target.value))} />
          </div>
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">نص الحديث *</label>
            <textarea className="input-field font-amiri text-base leading-relaxed" rows={4} value={text} onChange={(e) => setText(e.target.value)} />
          </div>
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">التصنيف</label>
            {!showNewCategory ? (
              <div className="flex gap-2">
                <select className="input-field flex-1" value={category} onChange={(e) => setCategory(e.target.value)}>
                  <option value="">اختر التصنيف...</option>
                  {categories.map((c) => <option key={c} value={c}>{c}</option>)}
                </select>
                <button className="btn btn-outline btn-sm" onClick={() => { setShowNewCategory(true); setCategory(""); }}>جديد</button>
              </div>
            ) : (
              <div className="flex gap-2">
                <input className="input-field flex-1" type="text" value={category} onChange={(e) => setCategory(e.target.value)} placeholder="اسم التصنيف الجديد" />
                <button className="btn btn-ghost btn-sm" onClick={() => setShowNewCategory(false)}>رجوع</button>
              </div>
            )}
          </div>
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">المرجع</label>
            <input className="input-field" type="text" value={reference} onChange={(e) => setReference(e.target.value)} />
          </div>
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">الشرح</label>
            <textarea className="input-field" rows={2} value={explanation} onChange={(e) => setExplanation(e.target.value)} />
          </div>
        </div>

        <div className="flex gap-3 mt-6">
          <button className="btn btn-outline btn-md flex-1" onClick={onClose}>إلغاء</button>
          <button className="btn btn-primary btn-md flex-1" onClick={submit} disabled={!text.trim() || !number}>
            <AppIcon name="check" size={18} />
            حفظ التعديلات
          </button>
        </div>
      </div>
    </div>
  );
}
