// src/app/shared/overlays/toast.component.ts
import { Component, inject } from '@angular/core';
import { ToastService } from '../services/toast.service';

import { AppIconComponent } from '../../shared/components/app-icon/app-icon.component';

@Component({
  selector: 'app-toast',
    imports: [AppIconComponent],
  template: `
    @if (toast.message(); as msg) {
    <button (click)="toast.message.set(null)" class="fixed bottom-6 right-6 z-50 px-5 py-3 bg-[var(--color-primary-dark)] text-white shadow-lg flex items-center gap-3 cursor-pointer border-none" aria-label="إخفاء الإشعار" role="alert" aria-live="polite">
      @if (toast.type() === 'error') {
        <app-icon name="error" [size]="18"></app-icon>
      } @else {
        <app-icon name="check_circle" [size]="18"></app-icon>
      }
      <span class="text-sm font-semibold">{{ msg }}</span>
      <span class="material-icons text-[var(--color-text-tertiary)] text-base mr-2" aria-hidden="true">close</span>
    </button>
    }
  `,
})
export class ToastComponent {
  toast = inject(ToastService);
}

// src/components/overlays/toast.tsx
"use client";

import { useUI } from "@/lib/tracker-context";
import AppIcon from "@/components/app-icon";

export default function Toast() {
  const { toast } = useUI();
  if (!toast.message) return null;

  return (
    <div className="fixed bottom-6 start-6 z-[60] max-w-[calc(100vw-3rem)]">
      <div role="status" aria-live="polite" aria-atomic="true" className="animate-fade-in">
        <div
          className={`flex items-center gap-3 px-4 py-3 text-sm font-semibold shadow-lg border ${toast.type === "success" ? "bg-green-light border-green text-tag-green-text" : "bg-rose-light border-rose text-rose"}`}
        >
          <AppIcon name={toast.type === "success" ? "check_circle" : "error"} size={18} />
          <span>{toast.message}</span>
          {toast.action && (
            <button
              type="button"
              className="underline font-bold ms-2 hover:opacity-80"
              onClick={() => { toast.action?.onClick(); toast.show(""); }}
            >
              {toast.action.label}
            </button>
          )}
          {!toast.action && (
            <button type="button" className="ms-2 hover:opacity-80" onClick={() => toast.show("")} aria-label="إغلاق">
              <AppIcon name="close" size={14} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
