// src/app/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useTracker } from "@/lib/tracker-context";
import AppIcon from "@/components/app-icon";

export default function LoginPage() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const { login } = useTracker();
  const router = useRouter();

  const handleLogin = async () => {
    if (!username || !password) return;
    setLoading(true);
    setError("");
    const result = await login(username, password);
    setLoading(false);
    if (result.success) {
      router.push("/dashboard");
    } else {
      setError(result.error || "فشل تسجيل الدخول");
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-canvas p-4">
      <div className="w-full max-w-sm bg-surface border border-border p-8">
        {/* Brand */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-primary-light mb-4">
            <AppIcon name="eco" size={32} className="text-primary" />
          </div>
          <h1 className="text-2xl font-bold text-text-primary font-tajawal">يا إخوتي</h1>
          <p className="text-sm text-text-secondary mt-1">نظام المتابعة الخاص بالحفظ والمراجعة</p>
        </div>

        {/* Error */}
        {error && (
          <div className="flex items-center gap-2 p-3 mb-4 bg-rose-light border border-rose text-rose text-sm">
            <AppIcon name="error_outline" size={18} />
            {error}
          </div>
        )}

        {/* Form */}
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">اسم المستخدم</label>
            <div className="relative">
              <span className="absolute right-3 top-1/2 -translate-y-1/2 text-text-tertiary">
                <AppIcon name="person" size={18} />
              </span>
              <input
                className="input-field pr-10"
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                placeholder="أدخل اسم المستخدم"
                dir="auto"
              />
            </div>
          </div>
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">كلمة المرور</label>
            <div className="relative">
              <span className="absolute right-3 top-1/2 -translate-y-1/2 text-text-tertiary">
                <AppIcon name="lock" size={18} />
              </span>
              <input
                className="input-field pr-10 pl-10"
                type={showPassword ? "text" : "password"}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="أدخل كلمة المرور"
              />
              <button
                type="button"
                className="absolute left-3 top-1/2 -translate-y-1/2 text-text-tertiary hover:text-text-secondary"
                onClick={() => setShowPassword(!showPassword)}
              >
                {showPassword ? <AppIcon name="visibility_off" size={16} /> : <AppIcon name="visibility" size={16} />}
              </button>
            </div>
          </div>
        </div>

        {/* Submit */}
        <button
          className="btn btn-primary btn-lg w-full mt-6"
          onClick={handleLogin}
          disabled={loading || !username || !password}
        >
          {loading ? (
            <span className="inline-block w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
          ) : (
            <>
              <AppIcon name="login" size={18} />
              تسجيل الدخول
            </>
          )}
        </button>

        <p className="text-center text-2xs text-text-tertiary mt-6">بسم الله الرحمن الرحيم</p>
      </div>
    </div>
  );
}

// src/app/pages/login/login.component.ts
import { Component, signal, inject, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../auth.service';
import { TrackerState } from '../../state';

import { AppIconComponent } from '../../shared/components/app-icon/app-icon.component';

@Component({
  selector: 'app-login',
  imports: [FormsModule, AppIconComponent],
  template: `
    <div class="login-wrapper">
      <div class="login-card">
        <!-- Logo / Brand -->
        <div class="login-brand">
          <div class="login-icon">
            <app-icon name="eco" [size]="20"></app-icon>
          </div>
          <h1 class="login-title">يا إخوتي</h1>
          <p class="login-subtitle">متابع الحفظ التفاعلي</p>
        </div>

        <!-- Login Form -->
        <form (ngSubmit)="onLogin()" class="login-form">
          <div class="input-group">
            <label for="username">اسم المستخدم</label>
            <div class="input-wrapper">
              <span class="input-icon"><app-icon name="person" [size]="18"></app-icon></span>
              <input
                id="username"
                type="text"
                [(ngModel)]="username"
                name="username"
                placeholder="أدخل اسم المستخدم"
                autocomplete="username"
                autofocus
                [disabled]="loading()"
              />
            </div>
          </div>

          <div class="input-group">
            <label for="password">كلمة المرور</label>
            <div class="input-wrapper">
              <span class="input-icon"><app-icon name="lock" [size]="18"></app-icon></span>
              <input
                id="password"
                [type]="showPassword() ? 'text' : 'password'"
                [(ngModel)]="password"
                name="password"
                placeholder="أدخل كلمة المرور"
                autocomplete="current-password"
                [disabled]="loading()"
              />
              <button
                type="button"
                class="toggle-pass"
                (click)="showPassword.set(!showPassword())"
                tabindex="-1"
              >
                <span class="material-icons">{{ showPassword() ? 'visibility_off' : 'visibility' }}</span>
              </button>
            </div>
          </div>

          @if (error()) {
            <div class="error-msg">
              <app-icon name="error_outline" [size]="18"></app-icon>
              <span>{{ error() }}</span>
            </div>
          }

              <button type="submit" class="btn btn-primary btn-lg w-full" [disabled]="loading() || !username || !password">
            @if (loading()) {
              <span class="spinner"></span>
              <span>جاري الدخول...</span>
            } @else {
              <app-icon name="login" [size]="18"></app-icon>
              <span>تسجيل الدخول</span>
            }
          </button>
        </form>

        <p class="login-footer">بسم الله الرحمن الرحيم</p>
      </div>
    </div>
  `,
  styles: `
    .login-wrapper {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background: var(--color-canvas);
      padding: 1rem;
    }

    .login-card {
      width: 100%;
      max-width: 400px;
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      padding: 2.5rem 2rem;
    }

    .login-brand {
      text-align: center;
      margin-bottom: 2rem;
    }

    .login-icon {
      width: 64px;
      height: 64px;
      background: var(--color-primary);
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 auto 1rem;
    }

    .login-title {
      font-family: var(--font-tajawal);
      font-size: 1.5rem;
      font-weight: 700;
      color: var(--color-text-primary);
      margin: 0;
    }

    .login-subtitle {
      font-size: 0.8rem;
      color: var(--color-text-secondary);
      margin-top: 0.25rem;
    }

    .login-form {
      display: flex;
      flex-direction: column;
      gap: 1.25rem;
    }

    .input-group label {
      display: block;
      font-size: 0.85rem;
      font-weight: 600;
      color: var(--color-text-primary);
      margin-bottom: 0.4rem;
    }

    .input-wrapper {
      position: relative;
      display: flex;
      align-items: center;
    }

    .input-icon {
      position: absolute;
      right: 0.75rem;
      color: var(--color-text-tertiary);
      font-size: 1.2rem;
      pointer-events: none;
    }

    .input-wrapper input {
      width: 100%;
      padding: 0.75rem 2.5rem 0.75rem 0.75rem;
      padding-right: 2.75rem;
      border: 1px solid var(--color-border);
      background: var(--color-canvas);
      font-family: var(--font-tajawal);
      font-size: 0.95rem;
      color: var(--color-text-primary);
      transition: border-color 0.15s;
      min-height: 48px;
    }

    .input-wrapper input:focus {
      outline: none;
      border-color: var(--color-primary);
      box-shadow: 0 0 0 3px var(--color-primary-light);
    }

    .input-wrapper input::placeholder {
      color: var(--color-text-tertiary);
    }

    .toggle-pass {
      position: absolute;
      left: 0.5rem;
      background: none;
      border: none;
      cursor: pointer;
      color: var(--color-text-tertiary);
      padding: 0.25rem;
      min-height: auto;
      display: flex;
      align-items: center;
    }

    .toggle-pass:hover {
      color: var(--color-text-secondary);
    }

    .error-msg {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.75rem 1rem;
      background: var(--color-rose-light);
      border: 1px solid var(--color-rose);
      color: var(--color-rose);
      font-size: 0.85rem;
      font-weight: 500;
    }

    .error-msg app-icon {
      font-size: 1.1rem;
    }

    .spinner {
      width: 18px;
      height: 18px;
      border: 2px solid rgba(255,255,255,0.3);
      border-top-color: white;
      border-radius: 50%;
      animation: spin 0.6s linear infinite;
    }

    @keyframes spin {
      to { transform: rotate(360deg); }
    }

    .login-footer {
      text-align: center;
      margin-top: 1.5rem;
      font-size: 0.75rem;
      color: var(--color-text-tertiary);
      font-family: var(--font-amiri);
    }
  `,
})
export class LoginComponent implements OnInit {
  private auth = inject(AuthService);
  private router = inject(Router);
  private state = inject(TrackerState);

  async ngOnInit() {
    const ok = await this.auth.checkAuth();
    if (ok) {
      await this.state.loadAll();
      this.router.navigate(['/dashboard']);
    }
  }

  username = '';
  password = '';
  loading = signal(false);
  error = signal('');
  showPassword = signal(false);

  async onLogin() {
    if (!this.username || !this.password) return;
    this.loading.set(true);
    this.error.set('');

    const result = await this.auth.login(this.username, this.password);
    this.loading.set(false);

    if (result.success) {
      await this.state.loadAll();
      this.router.navigate(['/dashboard']);
    } else {
      this.error.set(result.error || 'بيانات الدخول غير صحيحة');
    }
  }
}
