// src/components/containers/student-stage-card.tsx
"use client";

import type { Student } from "@/lib/types";
import { useTracker } from "@/lib/tracker-context";
import AppIcon from "@/components/app-icon";
import { getAvatarEmoji } from "@/lib/constants";

export default function StudentStageCard({ student }: { student: Student }) {
  const { getStudentStage, getStudentNextStageInfo } = useTracker();
  const stage = getStudentStage(student);
  const nextInfo = getStudentNextStageInfo(student);
  const isMaxed = !nextInfo;

  const progressPercent = isMaxed
    ? 100
    : Math.min(Math.round(((student.xp - stage.minXP) / (nextInfo!.nextStage.minXP - stage.minXP)) * 100), 100);

  return (
    <div className="panel p-5">
      <div className="flex items-start gap-4">
        <div className="text-3xl">{getAvatarEmoji(student.avatar)}</div>
        <div className="flex-1 min-w-0">
          <h3 className="text-lg font-bold text-text-primary font-tajawal">{student.name}</h3>
          <p className="text-sm text-text-secondary mt-0.5">{stage.name}</p>
          <p className="text-xs text-text-tertiary mt-2 leading-relaxed">{stage.description}</p>

          {isMaxed ? (
            <div className="mt-4 flex items-center gap-2 text-primary">
              <AppIcon name="emoji_events" size={20} />
              <span className="text-sm font-semibold">ما شاء الله! وصل لأعلى المراحل</span>
            </div>
          ) : (
            <div className="mt-4">
              <div className="flex justify-between text-xs text-text-tertiary mb-1.5">
                <span>{student.xp} XP</span>
                <span>{nextInfo!.nextStage.minXP} XP — {nextInfo!.remaining} متبقي</span>
              </div>
              <div className="progress-bar">
                <div className="progress-fill" style={{ width: `${progressPercent}%` }} />
              </div>
            </div>
          )}
        </div>
        <div className="flex-shrink-0 w-14 h-14 bg-primary-light flex items-center justify-center">
          <AppIcon name={stage.badgeIcon} size={28} className="text-primary-dark" />
        </div>
      </div>
    </div>
  );
}

// src/app/shared/containers/student-stage-card.component.ts
import { Component, inject, input } from '@angular/core';
import { TrackerState, Student } from '../../state';

import { AppIconComponent } from '../../shared/components/app-icon/app-icon.component';

@Component({
  selector: 'app-student-stage-card',
    imports: [AppIconComponent],
  template: `
    @let student = this.student();
    @let stage = state.getStudentStage(student);
    @let nextStageInfo = state.getStudentNextStageInfo(student);

    <div class="space-y-4 lg:col-span-1">
      <!-- Stage Card -->
      <div class="panel p-6 flex flex-col items-center text-center">
        <div class="w-16 h-16 rounded-none bg-[var(--color-primary-light)] flex items-center justify-center mb-4 relative">
          <span class="material-icons text-3xl text-[var(--color-primary)]">{{ stage.badgeIcon }}</span>
          @if (student.xp >= 10000) {
          <span class="absolute -top-1 -right-1 text-sm animate-bounce">👑</span>
          }
        </div>

        <span class="text-[11px] font-bold text-[var(--color-text-tertiary)] tracking-widest uppercase">المرحلة الحالية</span>
        <h4 class="font-tajawal text-xl font-bold text-[var(--color-text-primary)] mt-1">{{ stage.name }}</h4>
        <p class="text-xs text-[var(--color-text-secondary)] mt-2 leading-relaxed max-w-[200px]">{{ stage.description }}</p>

        <div class="w-full mt-5 p-4 bg-[var(--color-canvas)] border border-[var(--color-border-light)]">
          @if (nextStageInfo) {
          <p class="text-xs font-semibold text-[var(--color-text-secondary)] mb-2">
            يتبقى للوصول إلى <span class="text-[var(--color-primary-dark)] font-bold">{{ nextStageInfo.nextStage.name }}</span>:
          </p>
          <div class="flex items-center justify-between text-xs mb-1.5">
            <span class="text-[var(--color-primary-dark)] bg-[var(--color-primary-light)] px-2.5 py-0.5 rounded-none font-bold">
              {{ nextStageInfo.remaining }} نقطة
            </span>
            <span class="text-[var(--color-text-tertiary)] font-medium">{{ student.xp }} / {{ nextStageInfo.nextStage.minXP }}</span>
          </div>
          @let minTarget = nextStageInfo.nextStage.minXP; @let prevTarget = stage.minXP;
          @let currentInLevel = student.xp - prevTarget; @let totalRequiredInLevel = minTarget - prevTarget;
          @let percentageInLevel = (currentInLevel / totalRequiredInLevel) * 100;
          <div class="w-full bg-[var(--color-border)] rounded-none h-1.5 overflow-hidden mt-2 flex justify-end">
            <div class="bg-[var(--color-primary)] h-full rounded-none transition-all" [style.width.%]="percentageInLevel"></div>
          </div>
          } @else {
          <p class="text-xs font-bold text-[var(--color-green)] flex items-center justify-center gap-1">
            <app-icon name="emoji_events" [size]="18"></app-icon>
            ما شاء الله! وصل لأعلى المراحل
          </p>
          }
        </div>

        <div class="w-full flex justify-between items-center text-xs mt-4 pt-3 border-t border-[var(--color-border-light)]">
          <span class="text-[var(--color-text-secondary)] font-medium">النقاط الكلية:</span>
          <span class="font-bold text-[var(--color-text-primary)] bg-[var(--color-canvas)] px-3 py-1 rounded-none border border-[var(--color-border)]">
            {{ student.xp }} XP
          </span>
        </div>
      </div>

    </div>
  `,
})
export class StudentStageCardComponent {
  state = inject(TrackerState);
  student = input.required<Student>();

}
