// src/components/modals/add-hadith-modal.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { useTracker } from "@/lib/tracker-context";
import AppIcon from "@/components/app-icon";

export default function AddHadithModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { state, addHadith } = useTracker();
  const [text, setText] = useState("");
  const [reference, setReference] = useState("رواية صحيحة");
  const [explanation, setExplanation] = useState("");
  const [category, setCategory] = useState("");
  const [showNewCategory, setShowNewCategory] = useState(false);

  const categories = [...new Set(state.hadiths.map((h) => h.category).filter(Boolean))].sort();

  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    if (open) window.addEventListener("keydown", handleEsc);
    return () => window.removeEventListener("keydown", handleEsc);
  }, [open, onClose]);

  const submit = useCallback(async () => {
    if (!text.trim()) return;
    await addHadith(text.trim(), reference.trim(), explanation.trim(), category.trim());
    setText(""); setReference("رواية صحيحة"); setExplanation(""); setCategory("");
    onClose();
  }, [text, reference, explanation, category, addHadith, onClose]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center" role="dialog" aria-modal="true">
      <div className="absolute inset-0 bg-overlay" onClick={onClose} />
      <div className="relative modal-panel max-w-lg animate-fade-in">
        <div className="flex items-center justify-between mb-6">
          <h2 className="panel-title">
            <AppIcon name="add_box" size={20} className="text-primary" />
            إضافة حديث شريف جديد
          </h2>
          <button className="btn btn-icon btn-ghost" onClick={onClose}><AppIcon name="close" size={18} /></button>
        </div>

        <div className="space-y-4">
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">نص الحديث *</label>
            <textarea
              className="input-field font-amiri text-base leading-relaxed"
              rows={4}
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="اكتب نص الحديث الشريف..."
            />
          </div>
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">التصنيف</label>
            {!showNewCategory ? (
              <div className="flex gap-2">
                <select className="input-field flex-1" value={category} onChange={(e) => setCategory(e.target.value)}>
                  <option value="">اختر التصنيف...</option>
                  {categories.map((c) => <option key={c} value={c}>{c}</option>)}
                </select>
                <button className="btn btn-outline btn-sm" onClick={() => { setShowNewCategory(true); setCategory(""); }}>جديد</button>
              </div>
            ) : (
              <div className="flex gap-2">
                <input className="input-field flex-1" type="text" value={category} onChange={(e) => setCategory(e.target.value)} placeholder="اسم التصنيف الجديد" />
                <button className="btn btn-ghost btn-sm" onClick={() => setShowNewCategory(false)}>رجوع</button>
              </div>
            )}
          </div>
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">المرجع</label>
            <input className="input-field" type="text" value={reference} onChange={(e) => setReference(e.target.value)} />
          </div>
          <div>
            <label className="block text-sm font-semibold text-text-secondary mb-1">الشرح</label>
            <textarea className="input-field" rows={2} value={explanation} onChange={(e) => setExplanation(e.target.value)} placeholder="شرح مبسط للحديث..." />
          </div>
        </div>

        <div className="flex gap-3 mt-6">
          <button className="btn btn-outline btn-md flex-1" onClick={onClose}>إلغاء</button>
          <button className="btn btn-primary btn-md flex-1" onClick={submit} disabled={!text.trim()}>
            <AppIcon name="check" size={18} />
            إضافة الحديث
          </button>
        </div>
      </div>
    </div>
  );
}

// src/app/shared/modals/add-hadith-modal.component.ts
import { Component, inject, signal, OnInit, HostListener } from '@angular/core';
import { FormsModule, ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { TrackerState } from '../../state';
import { ToastService } from '../services/toast.service';
import { ModalService } from '../services/modal.service';

import { AppIconComponent } from '../../shared/components/app-icon/app-icon.component';

@Component({
  selector: 'app-add-hadith-modal',
  imports: [CommonModule, FormsModule, ReactiveFormsModule, AppIconComponent],
  template: `
    @if (modal.showAddHadith()) {
    <div class="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="addHadithTitle" (click)="close()">
      <div class="modal-panel max-w-lg" (click)="$event.stopPropagation()">
        <div class="flex items-center justify-between mb-5 pb-4 border-b border-[var(--color-border-light)]">
          <h3 id="addHadithTitle" class="font-tajawal text-lg font-bold text-[var(--color-text-primary)] flex items-center gap-2">
            <app-icon name="add_box" [size]="18"></app-icon>
            إضافة حديث شريف جديد
          </h3>
          <button (click)="modal.showAddHadith.set(false)" class="btn btn-ghost btn-icon" aria-label="إغلاق">
            <app-icon name="close" [size]="18"></app-icon>
          </button>
        </div>

        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4">
          <div>
            <label for="addHadithText" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">نص الحديث *</label>
            <textarea id="addHadithText" formControlName="text" rows="3" placeholder="نص الحديث..."
              class="input-field font-amiri text-lg text-center"></textarea>
            @if (form.get('text')?.invalid && form.get('text')?.touched) {
            <p class="text-[11px] text-[var(--color-rose)] mt-1">النص مطلوب (5 أحرف على الأقل).</p>
            }
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div>
              <label for="addHadithCategory" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">القسم / الباب *</label>
              @if (showNewCategoryInput()) {
              <div class="flex gap-2">
                <input id="addHadithCategory" type="text" formControlName="category" placeholder="اسم التصنيف الجديد"
                  class="input-field flex-1" />
                <button type="button" (click)="useExistingCategory()"
                  class="btn btn-sm border border-[var(--color-border)] bg-[var(--color-surface)] hover:bg-[var(--color-canvas)] whitespace-nowrap">
                  اختر من القائمة
                </button>
              </div>
              } @else if (uniqueCategories().length > 0) {
              <div class="flex gap-2">
                <select id="addHadithCategory" formControlName="category"
                  class="input-field flex-1 cursor-pointer">
                  @for (cat of uniqueCategories(); track cat) {
                  <option [value]="cat">{{ cat }}</option>
                  }
                </select>
                <button type="button" (click)="showNewCategoryInput.set(true)"
                  class="btn btn-sm border border-[var(--color-border)] bg-[var(--color-surface)] hover:bg-[var(--color-canvas)] whitespace-nowrap">
                  جديد
                </button>
              </div>
              } @else {
              <input id="addHadithCategory" type="text" formControlName="category" placeholder="مثال: الأخلاق والصدق"
                class="input-field" />
              }
            </div>
            <div>
              <label for="addHadithReference" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">راوي الحديث *</label>
              <input id="addHadithReference" type="text" formControlName="reference" placeholder="مثال: عن أبي هريرة"
                class="input-field" />
            </div>
          </div>

          <div>
            <label for="addHadithExplanation" class="block text-xs font-semibold text-[var(--color-text-secondary)] mb-1.5">الشرح والتوجيه التربوي *</label>
            <textarea id="addHadithExplanation" formControlName="explanation" rows="3" placeholder="شرح بسيط لمساعدة الأطفال..."
              class="input-field"></textarea>
          </div>

          <div class="flex items-center gap-3 pt-2">
            <button type="submit" [disabled]="form.invalid"
              class="btn btn-primary btn-md flex-1 disabled:opacity-50 disabled:cursor-not-allowed">
              <app-icon name="check" [size]="18"></app-icon>
              إضافة الحديث
            </button>
            <button type="button" (click)="modal.showAddHadith.set(false)"
              class="btn btn-outline btn-md">
              إلغاء
            </button>
          </div>
        </form>
      </div>
    </div>
    }
  `,
})
export class AddHadithModalComponent implements OnInit {
  state = inject(TrackerState);
  toast = inject(ToastService);
  modal = inject(ModalService);

  showNewCategoryInput = signal(false);

  form = new FormGroup({
    text: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.minLength(5)] }),
    reference: new FormControl('رواه البخاري ومسلم', { nonNullable: true, validators: [Validators.required] }),
    explanation: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    category: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
  });

  ngOnInit() {
    const cats = this.uniqueCategories();
    if (cats.length > 0) {
      this.form.patchValue({ category: cats[0] });
    }
  }

  uniqueCategories() {
    const cats = new Set<string>();
    this.state.hadiths().forEach((h) => cats.add(h.category));
    return Array.from(cats);
  }

  useExistingCategory() {
    this.showNewCategoryInput.set(false);
    const cats = this.uniqueCategories();
    if (cats.length > 0) {
      this.form.patchValue({ category: cats[0] });
    }
  }

  onSubmit() {
    if (this.form.invalid) return;
    const val = this.form.value;
    const cat = val.category || 'عام';
    this.state.addHadith(val.text || '', val.reference || '', val.explanation || '', cat);
    this.modal.showAddHadith.set(false);
    this.form.reset({ reference: 'رواه البخاري ومسلم' });
    this.showNewCategoryInput.set(false);
    this.toast.show('تم إضافة الحديث الشريف بنجاح!');
  }

  close() {
    this.modal.showAddHadith.set(false);
  }

  @HostListener('document:keydown.escape')
  onEscape() {
    this.close();
  }
}
