// src/components/layout/sidebar.tsx
"use client";

import { useRouter, usePathname } from "next/navigation";
import { useEffect, useCallback } from "react";
import { useTracker } from "@/lib/tracker-context";
import AppIcon from "@/components/app-icon";
import { getAvatarEmoji } from "@/lib/constants";

interface NavItem {
  label: string;
  path: string;
  icon: string;
  section: "مسارات التعلم" | "أدوات";
}

const NAV_ITEMS: NavItem[] = [
  { label: "الرئيسية", path: "/dashboard", icon: "home", section: "مسارات التعلم" },
  { label: "مسار الأحاديث", path: "/hadith", icon: "menu_book", section: "مسارات التعلم" },
  { label: "مسار القرآن", path: "/quran", icon: "auto_stories", section: "مسارات التعلم" },
  { label: "مسار الإنجليزية", path: "/english", icon: "translate", section: "مسارات التعلم" },
  { label: "المناهج التعليمية", path: "/reference", icon: "library_books", section: "أدوات" },
  { label: "لوحة الإدارة", path: "/stages", icon: "manage_accounts", section: "أدوات" },
];

export default function Sidebar() {
  const router = useRouter();
  const pathname = usePathname();
  const { state, logout, getStudentStage } = useTracker();
  const student = state.students.find((s) => s.id === state.selectedStudentId) || null;
  const stage = student ? getStudentStage(student) : null;

  const navTo = useCallback((path: string) => { router.push(path); }, [router]);
  const handleLogout = useCallback(async () => { await logout(); router.push("/login"); }, [logout, router]);

  const contextPath = pathname.split("/")[1] || "dashboard";
  const progressLabel: Record<string, string> = { hadith: "حدث", quran: "سورة", english: "وحدة" };
  const getProgressValue = () => {
    if (!student) return { done: 0, total: 0, label: "" };
    switch (contextPath) {
      case "hadith": return { done: student.memorizedHadithNumbers.length, total: state.hadiths.length, label: progressLabel.hadith };
      case "quran": return { done: student.memorizedSurahNumbers.length, total: 114, label: progressLabel.quran };
      case "english": return { done: student.memorizedEnglishUnits.length, total: state.englishUnits.length, label: progressLabel.english };
      default: return { done: 0, total: 0, label: "" };
    }
  };
  const progress = getProgressValue();

  return (
    <aside className="hidden lg:flex h-full w-64 bg-nav text-nav-text flex-col">
      {/* Brand */}
      <div className="flex items-center gap-2 p-4 border-b border-nav-active">
        <AppIcon name="eco" size={22} className="text-primary" />
        <span className="text-lg font-bold font-tajawal">يا إخوتي</span>
      </div>

      {/* Student card */}
      {student && (
        <div className="p-4 border-b border-nav-active">
          <div className="flex items-center gap-3">
            <span className="text-2xl">{getAvatarEmoji(student.avatar)}</span>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold truncate">{student.name}</p>
              <p className="text-2xs text-nav-text-muted">{stage?.name}</p>
              {progress.total > 0 && (
                <div className="mt-2">
                  <div className="flex justify-between text-2xs text-nav-text-muted mb-1">
                    <span>{progress.done} / {progress.total} {progress.label}</span>
                  </div>
                  <div className="progress-bar bg-nav-active">
                    <div className="progress-fill" style={{ width: `${Math.round((progress.done / progress.total) * 100)}%` }} />
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Navigation */}
      <nav className="flex-1 overflow-y-auto p-3 space-y-6">
        {(["مسارات التعلم", "أدوات"] as const).map((section) => (
          <div key={section}>
            <p className="text-2xs font-semibold text-nav-text-subtle uppercase tracking-wider mb-2 px-2">{section}</p>
            <ul className="space-y-1">
              {NAV_ITEMS.filter((item) => item.section === section).map((item) => {
                const active = pathname.startsWith(item.path);
                return (
                  <li key={item.path}>
                    <button
                      className={`w-full flex items-center gap-3 px-3 py-2.5 text-sm font-medium rounded-none transition-colors ${active ? "bg-nav-active text-primary" : "text-nav-text-muted hover:bg-nav-hover hover:text-nav-text"}`}
                      onClick={() => navTo(item.path)}
                      aria-current={active ? "page" : undefined}
                    >
                      <AppIcon name={item.icon} size={18} />
                      {item.label}
                    </button>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </nav>

      {/* Footer */}
      <div className="p-4 border-t border-nav-active">
        <button className="w-full flex items-center gap-3 px-3 py-2.5 text-sm text-nav-text-muted hover:bg-nav-hover hover:text-nav-text transition-colors rounded-none" onClick={handleLogout}>
          <AppIcon name="logout" size={18} />
          تسجيل الخروج
        </button>
        <div className="mt-3 text-center">
          <span className="text-2xs text-nav-text-subtle flex items-center justify-center gap-1">
            <AppIcon name="verified" size={12} />
            v1.0 — متابع الحفظ
          </span>
        </div>
      </div>
    </aside>
  );
}

// src/app/shared/layout/sidebar.component.ts
import { Component, inject } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { TrackerState } from '../../state';
import { AuthService } from '../../auth.service';

@Component({
  selector: 'app-sidebar',
  imports: [RouterLink, RouterLinkActive],
  template: `
    <aside class="w-full md:w-64 bg-[var(--color-nav)] flex flex-col justify-between shrink-0">
      <div class="p-5">
        <!-- App Identity -->
        <div class="flex items-center gap-3 mb-8 pb-6 border-b border-white/10">
          <div class="w-10 h-10 rounded-none bg-[var(--color-primary)] flex items-center justify-center">
            <span class="material-icons text-white text-xl">eco</span>
          </div>
          <div>
            <h1 class="font-inter text-lg font-bold text-white tracking-tight">يا إخوتي</h1>
            <p class="text-xs text-[var(--color-text-inverse-muted)] font-medium">متابع الحفظ التفاعلي</p>
          </div>
        </div>

        <!-- Selected Student Card -->
        @if (state.selectedStudent(); as student) {
        <div class="mb-6 p-4 rounded-none bg-white/5 border border-white/5">
          <div class="flex items-center gap-2 mb-3">
            <div class="w-2 h-2 rounded-none bg-[var(--color-green)]"></div>
            <p class="text-[11px] text-[var(--color-text-inverse-muted)] font-semibold uppercase tracking-wider">الطالب المحدد</p>
          </div>
          <div class="flex items-center gap-2.5 mb-3">
            <span class="text-xl">{{ getAvatarEmoji(student.avatar) }}</span>
            <span class="font-bold text-white text-sm">{{ student.name }}</span>
          </div>
          <div class="flex items-center justify-between text-xs">
            <span class="text-[var(--color-text-inverse-muted)]">{{ getProgressLabel() }}:</span>
            <span class="font-semibold text-[var(--color-primary)]">{{ getProgressValue(student) }}</span>
          </div>
          <div class="flex items-center justify-between text-xs mt-2">
            <span class="text-[var(--color-text-inverse-muted)]">المرحلة:</span>
            <span class="font-semibold text-[var(--color-amber)]">{{ getStudentStageName(student) }}</span>
          </div>
        </div>
        }

        <!-- Navigation -->
        <nav class="space-y-1">
          <a routerLink="/dashboard" routerLinkActive="bg-white/10 text-white" [routerLinkActiveOptions]="{ exact: true }"
            class="flex items-center gap-3 px-4 py-2.5 rounded-none text-[var(--color-text-inverse-muted)] hover:bg-white/5 hover:text-white transition-all text-sm font-medium">
            <span class="material-icons text-xl">home</span>
            <span>الرئيسية</span>
          </a>

          <div class="pt-2 pb-1">
            <p class="px-4 text-[10px] font-bold text-[var(--color-text-inverse-muted)]/50 uppercase tracking-widest mb-1">مسارات التعلم</p>
          </div>
          <a routerLink="/hadith" routerLinkActive="bg-white/10 text-white"
            class="flex items-center gap-3 px-4 py-2.5 rounded-none text-[var(--color-text-inverse-muted)] hover:bg-white/5 hover:text-white transition-all text-sm font-medium">
            <span class="material-icons text-xl">menu_book</span>
            <span>مسار الأحاديث</span>
          </a>
          <a routerLink="/quran" routerLinkActive="bg-white/10 text-white"
            class="flex items-center gap-3 px-4 py-2.5 rounded-none text-[var(--color-text-inverse-muted)] hover:bg-white/5 hover:text-white transition-all text-sm font-medium">
            <span class="material-icons text-xl">auto_stories</span>
            <span>مسار القرآن</span>
          </a>
          <a routerLink="/english" routerLinkActive="bg-white/10 text-white"
            class="flex items-center gap-3 px-4 py-2.5 rounded-none text-[var(--color-text-inverse-muted)] hover:bg-white/5 hover:text-white transition-all text-sm font-medium">
            <span class="material-icons text-xl">translate</span>
            <span>مسار الإنجليزية</span>
          </a>

          <div class="pt-4 pb-1">
            <p class="px-4 text-[10px] font-bold text-[var(--color-text-inverse-muted)]/50 uppercase tracking-widest mb-1">أدوات</p>
          </div>
          <a routerLink="/reference" routerLinkActive="bg-white/10 text-white"
            class="flex items-center gap-3 px-4 py-2.5 rounded-none text-[var(--color-text-inverse-muted)] hover:bg-white/5 hover:text-white transition-all text-sm font-medium">
            <span class="material-icons text-xl">library_books</span>
            <span>المناهج التعليمية</span>
          </a>
          <a routerLink="/stages" routerLinkActive="bg-white/10 text-white"
            class="flex items-center gap-3 px-4 py-2.5 rounded-none text-[var(--color-text-inverse-muted)] hover:bg-white/5 hover:text-white transition-all text-sm font-medium">
            <span class="material-icons text-xl">manage_accounts</span>
            <span>لوحة الإدارة</span>
          </a>
        </nav>
      </div>

      <!-- Bottom Section -->
      <div class="p-5 border-t border-white/10">
        <button
          (click)="logout()"
          class="flex items-center gap-3 w-full px-4 py-2.5 rounded-none text-[var(--color-text-inverse-muted)] hover:bg-red-500/10 hover:text-red-400 transition-all text-sm font-medium cursor-pointer mb-2"
        >
          <span class="material-icons text-xl">logout</span>
          <span>تسجيل الخروج</span>
        </button>
        <div class="flex items-center gap-3 px-3 py-2 rounded-none bg-white/5 text-[var(--color-text-inverse-muted)] text-xs">
          <span class="material-icons text-sm">verified</span>
          <span class="font-medium">v1.0 — متابع الحفظ</span>
        </div>
      </div>
    </aside>
  `,
})
export class SidebarComponent {
  state = inject(TrackerState);
  private router = inject(Router);
  private auth = inject(AuthService);

  avatarMap: Record<string, string> = {
    'avatar-leaf': '🌿',
    'avatar-mountain': '🏔️',
    'avatar-sun': '☀️',
    'avatar-flower': '🌸',
    'avatar-water': '💧',
    'avatar-shield': '🛡️',
  };

  getAvatarEmoji(key: string): string {
    return this.avatarMap[key] || '🌿';
  }

  getStudentStageName(student: { id: string; name: string; xp: number }): string {
    const stage = this.state.getStudentStage({ xp: student.xp } as import('../../state').Student);
    return stage?.name || '';
  }

  getProgressLabel(): string {
    const url = this.router.url;
    if (url.includes('/quran')) return 'السور';
    if (url.includes('/english')) return 'المفردات';
    return 'الأحاديث';
  }

  getProgressValue(student: { memorizedHadithNumbers: number[]; memorizedSurahNumbers: number[]; memorizedEnglishUnits: number[] }): string {
    const url = this.router.url;
    if (url.includes('/quran')) {
      return `${student.memorizedSurahNumbers.length} / 114`;
    }
    if (url.includes('/english')) {
      const totalUnits = this.state.englishUnits().length;
      return `${student.memorizedEnglishUnits.length} / ${totalUnits}`;
    }
    return `${student.memorizedHadithNumbers.length} / ${this.state.hadiths().length}`;
  }

  isTracksMenuActive(): boolean {
    const url = this.router.url;
    return url.includes('/quran') || url.includes('/hadith') || url.includes('/english');
  }

  logout() {
    this.auth.logout();
  }
}
