// src/app/pages/reference/reference.component.ts
import { Component, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { TrackerState, QURAN_SURAHS } from '../../state';
import { Hadith } from '../../hadith-data';
import { ToastService } from '../../shared/services/toast.service';
import { ModalService } from '../../shared/services/modal.service';

import { AppIconComponent } from '../../shared/components/app-icon/app-icon.component';

@Component({
  selector: 'app-reference',
  imports: [CommonModule, AppIconComponent],
  template: `
    <div class="space-y-5">
      <div class="panel p-5 flex items-center gap-4">
        <label for="referenceSubject" class="text-xs font-semibold text-[var(--color-text-secondary)] whitespace-nowrap">المنهج:</label>
        <div class="relative flex-1 max-w-xs">
          <select id="referenceSubject" (change)="activeReferenceSubject.set($any($event.target).value)"
            class="w-full appearance-none border border-[var(--color-border)] bg-[var(--color-canvas)] px-4 py-2.5 text-sm font-semibold text-[var(--color-text-primary)] focus:outline-none focus:border-[var(--color-primary)] transition-colors cursor-pointer">
            <option value="hadith">الأحاديث الشريفة</option>
            <option value="quran">سور القرآن الكريم</option>
            <option value="english">المفردات الإنجليزية</option>
          </select>
          <span class="absolute left-3 top-1/2 pointer-events-none icon-expand-more"><app-icon name="expand_more" [size]="18"></app-icon></span>
        </div>
      </div>

      @if (activeReferenceSubject() === 'hadith') {
      <div class="flex flex-col sm:flex-row items-center justify-between gap-4 p-5 bg-[var(--color-primary-light)] border" [style.border-color]="'color-mix(in srgb, var(--color-primary) 10%, transparent)'">
        <div>
          <h3 class="panel-title">
            <span class="panel-title-icon">library_books</span>
            دليل الأحاديث الشريفة
          </h3>
          <p class="text-xs text-[var(--color-text-secondary)] mt-1">تصفح وأضف أو عدّل الأحاديث النبوية</p>
        </div>
        <button (click)="modal.showAddHadith.set(true)"
          class="btn btn-primary btn-md">
          <app-icon name="add_circle" [size]="18"></app-icon>
          إضافة حديث جديد
        </button>
      </div>

      <div class="panel p-4 flex flex-col md:flex-row gap-3 items-center justify-between">
        <div class="w-full md:max-w-md relative">
          <span class="absolute right-3 top-1/2 select-none"><app-icon name="search" [size]="18"></app-icon></span>
          <input type="text" [value]="state.searchQuery()" (input)="onSearchChange($event)"
            placeholder="ابحث برقم الحديث أو الباب أو النص..."
            class="w-full border border-[var(--color-border)] bg-[var(--color-canvas)] pr-10 pl-4 py-2.5 text-sm focus:outline-none focus:border-[var(--color-primary)] placeholder-[var(--color-text-tertiary)] transition-colors" />
        </div>
        <div class="flex flex-wrap gap-1.5 justify-center">
          <button (click)="onCategorySelect('all')"
            [class]="state.categoryFilter() === 'all' ? 'btn btn-primary btn-sm' : 'btn btn-outline btn-sm'">
            الكل
          </button>
          @for (cat of uniqueCategories(); track cat) {
          <button (click)="onCategorySelect(cat)"
            [class]="state.categoryFilter() === cat ? 'btn btn-primary btn-sm' : 'btn btn-outline btn-sm'">
            {{ cat }}
          </button>
          }
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
        @for (hadith of filteredHadiths(); track hadith.number) {
        <div class="panel p-5 flex flex-col justify-between">
          <div>
            <div class="flex items-center justify-between pb-3 mb-3 border-b border-[var(--color-border-light)]">
              <div class="flex items-center gap-2">
                <span class="w-12 h-12 bg-[var(--color-canvas)] border border-[var(--color-border)] flex items-center justify-center font-bold text-xs text-[var(--color-text-primary)]">{{ hadith.number }}</span>
                <span class="tag tag-primary">{{ hadith.category }}</span>
              </div>
              <div class="flex items-center gap-1">
                <button (click)="openEditHadith(hadith)" class="btn btn-ghost btn-icon" title="تعديل" aria-label="تعديل الحديث">
                  <app-icon name="edit" [size]="18"></app-icon>
                </button>
                <button (click)="onDeleteHadith(hadith.number, hadith.category)" class="btn btn-ghost btn-icon hover:text-[var(--color-rose)] hover:bg-[var(--color-rose-light)]" title="حذف" aria-label="حذف الحديث">
                  <app-icon name="delete" [size]="18"></app-icon>
                </button>
              </div>
            </div>
            <h4 class="font-tajawal text-sm font-bold text-[var(--color-text-primary)] mb-2">باب: {{ hadith.category }}</h4>
            <p class="font-amiri text-[var(--color-primary-dark)] text-base leading-relaxed p-3 text-center mb-3" [style.background-color]="'color-mix(in srgb, var(--color-primary-light) 50%, transparent)'">"{{ hadith.text }}"</p>
            <p class="text-xs text-[var(--color-text-secondary)] mb-3 leading-relaxed">{{ hadith.explanation }}</p>
          </div>
          <div class="border-t border-[var(--color-border-light)] pt-3 flex items-center justify-between">
            <span class="text-[11px] text-[var(--color-text-tertiary)] font-medium">الراوي: {{ hadith.reference }}</span>
            <button (click)="viewInTrail()" class="text-xs font-semibold text-[var(--color-primary)] hover:text-[var(--color-primary-dark)] flex items-center gap-1 cursor-pointer transition-colors">
              <app-icon name="arrow_back" [size]="18"></app-icon>
              عرض في المسار
            </button>
          </div>
        </div>
        } @empty {
        <div class="col-span-2 empty-state">
          <span class="empty-state-icon">manage_search</span>
          <p class="empty-state-text">لم نعثر على أحاديث تطابق البحث</p>
        </div>
        }
      </div>
      }

      @if (activeReferenceSubject() === 'quran') {
      <div class="p-5 bg-[var(--color-primary-light)] border" [style.border-color]="'color-mix(in srgb, var(--color-primary) 10%, transparent)'">
        <h3 class="panel-title">
          <span class="panel-title-icon">auto_stories</span>
          دليل القرآن الكريم
        </h3>
        <p class="text-xs text-[var(--color-text-secondary)] mt-1">استعرض السور القرآنية وعدد صفحاتها</p>
      </div>
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        @for (surah of allSurahs; track surah.number) {
        <div class="panel p-4 text-center hover:border-[var(--color-primary)] transition-colors cursor-pointer">
          <div class="w-10 h-10 mx-auto bg-[var(--color-primary-light)] flex items-center justify-center font-bold text-[var(--color-primary)] text-sm mb-2">{{ surah.number }}</div>
          <h4 class="font-tajawal font-bold text-sm text-[var(--color-text-primary)] mb-1">سورة {{ surah.name }}</h4>
          @if (surah.pagesCount) {
          <span class="tag tag-green">{{ surah.pagesCount }} صفحة</span>
          }
        </div>
        }
      </div>
      }

      @if (activeReferenceSubject() === 'english') {
      <div class="flex flex-col sm:flex-row items-center justify-between gap-4 p-5 bg-[var(--color-primary-light)] border"
        [style.border-color]="'color-mix(in srgb, var(--color-primary) 10%, transparent)'">
        <div>
          <h3 class="panel-title">
            <span class="panel-title-icon">translate</span>
            دليل المفردات الإنجليزية
          </h3>
          <p class="text-xs text-[var(--color-text-secondary)] mt-1">الوحدات والكلمات</p>
        </div>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
        @for (unit of state.englishUnits(); track unit.unitNumber) {
        <div class="panel p-5">
          <div class="flex justify-between items-start mb-3 pb-3 border-b border-[var(--color-border-light)]">
            <h4 class="font-tajawal font-bold text-[var(--color-text-primary)] flex items-center gap-2">
              <app-icon name="list_alt" [size]="18"></app-icon>
              الوحدة {{ unit.unitNumber }}
            </h4>
            <span class="text-xs text-[var(--color-text-secondary)]">{{ unit.words.length }} كلمة</span>
          </div>
          <div class="space-y-1.5">
            @for (word of unit.words; track $index) {
            <div class="flex justify-between items-center text-sm p-2.5 bg-[var(--color-canvas)] border border-[var(--color-border-light)]">
              <span class="font-bold text-[var(--color-text-primary)] text-sm">{{ word.word }}</span>
              <span class="text-[var(--color-text-secondary)] text-xs">{{ word.definition }}</span>
            </div>
            }
          </div>
        </div>
        } @empty {
        <div class="col-span-1 md:col-span-2 empty-state">
          <span class="empty-state-icon">translate</span>
          <p class="empty-state-text">لا توجد وحدات إنجليزية بعد</p>
        </div>
        }
      </div>
      }
    </div>
  `,
})
export class ReferenceComponent {
  state = inject(TrackerState);
  toast = inject(ToastService);
  modal = inject(ModalService);
  private router = inject(Router);

  activeReferenceSubject = signal<'hadith' | 'quran' | 'english'>('hadith');
  allSurahs = QURAN_SURAHS;

  filteredHadiths = computed(() => {
    const query = this.state.searchQuery().trim().toLowerCase();
    const cat = this.state.categoryFilter();
    return this.state.hadiths().filter((h) => {
      const matchesQuery =
        h.category.toLowerCase().includes(query) ||
        h.text.toLowerCase().includes(query) ||
        h.number.toString() === query ||
        h.explanation.toLowerCase().includes(query);
      const matchesCategory = cat === 'all' || h.category === cat;
      return matchesQuery && matchesCategory;
    });
  });

  uniqueCategories = computed(() => {
    const cats = new Set<string>();
    this.state.hadiths().forEach((h) => cats.add(h.category));
    return Array.from(cats);
  });

  onSearchChange(event: Event) {
    const target = event.target as HTMLInputElement;
    this.state.searchQuery.set(target.value);
  }

  onCategorySelect(cat: string) {
    this.state.categoryFilter.set(cat);
  }

  openEditHadith(hadith: Hadith) {
    window.dispatchEvent(new CustomEvent('editHadith', { detail: hadith }));
  }

  onDeleteHadith(number: number, category: string) {
    this.modal.confirm(`هل أنت متأكد من حذف الحديث الشريف ضمن باب (${category})؟`, () => {
      this.state.deleteHadith(number);
      this.toast.show('تم حذف الحديث الشريف وسجلاته.');
      this.modal.confirmState.set(null);
    });
  }

  viewInTrail() {
    this.router.navigate(['/hadith']);
  }

}

// src/app/reference/page.tsx
"use client";

import { useState, useMemo } from "react";
import { useRouter } from "next/navigation";
import { useTracker } from "@/lib/tracker-context";
import AppIcon from "@/components/app-icon";
import { QURAN_SURAHS } from "@/lib/constants";
import EditHadithModal from "@/components/modals/edit-hadith-modal";
import type { Hadith } from "@/lib/types";

type ReferenceSubject = "hadith" | "quran" | "english";

export default function ReferencePage() {
  const { state, selectStudent, deleteHadith, confirm } = useTracker();
  const router = useRouter();
  const [subject, setSubject] = useState<ReferenceSubject>("hadith");
  const [searchQuery, setSearchQuery] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [editHadith, setEditHadith] = useState<Hadith | null>(null);

  const uniqueCategories = useMemo(
    () => [...new Set(state.hadiths.map((h) => h.category).filter(Boolean))].sort(),
    [state.hadiths]
  );

  const filteredHadiths = useMemo(() => {
    let result = state.hadiths;
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      result = result.filter((h) => h.text.includes(q) || h.category.includes(q) || h.reference.includes(q));
    }
    if (categoryFilter !== "all") result = result.filter((h) => h.category === categoryFilter);
    return result;
  }, [state.hadiths, searchQuery, categoryFilter]);

  const handleDeleteHadith = (number: number) => {
    confirm.ask("هل أنت متأكد من حذف هذا الحديث؟", () => deleteHadith(number));
  };

  return (
    <div className="space-y-6">
      {/* Subject selector */}
      <div className="flex gap-2">
        {(["hadith", "quran", "english"] as const).map((s) => (
          <button
            key={s}
            className={`btn btn-md ${subject === s ? "btn-primary" : "btn-outline"}`}
            onClick={() => setSubject(s)}
          >
            {s === "hadith" ? "الأحاديث" : s === "quran" ? "القرآن" : "الإنجليزية"}
          </button>
        ))}
      </div>

      {subject === "hadith" && (
        <div className="panel p-6">
          <div className="panel-header">
            <h3 className="panel-title"><span className="panel-title-icon">📚</span> الأحاديث النبوية</h3>
            <div className="flex items-center gap-2">
              <div className="relative">
                <span className="absolute right-3 top-1/2 -translate-y-1/2 text-text-tertiary"><AppIcon name="search" size={14} /></span>
                <input className="input-field pr-8 text-sm" type="text" value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="بحث في الأحاديث..." />
              </div>
              <select className="input-field text-sm" style={{ width: "auto" }} value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}>
                <option value="all">كل التصنيفات</option>
                {uniqueCategories.map((c) => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {filteredHadiths.map((h) => (
              <div key={h.number} className="panel bg-canvas p-4">
                <div className="flex items-start justify-between mb-2">
                  <span className="tag tag-primary">رقم {h.number}</span>
                  <div className="flex gap-1">
                    <button className="btn btn-icon btn-ghost" title="تعديل" onClick={() => setEditHadith(h)}><AppIcon name="edit" size={16} /></button>
                    <button className="btn btn-icon btn-ghost" title="حذف" onClick={() => handleDeleteHadith(h.number)}><AppIcon name="delete" size={16} /></button>
                  </div>
                </div>
                <p className="font-amiri text-sm font-bold text-text-primary leading-relaxed mb-2">&ldquo;{h.text}&rdquo;</p>
                <p className="text-xs text-text-secondary mb-1">{h.reference}</p>
                <span className="tag tag-amber text-2xs">{h.category}</span>
                <button
                  className="btn btn-ghost btn-sm mt-3 text-primary flex items-center gap-1"
                  onClick={() => { selectStudent(state.students[0]?.id || ""); router.push("/hadith"); }}
                >
                  <AppIcon name="arrow_back" size={14} /> عرض في المسار
                </button>
              </div>
            ))}
            {filteredHadiths.length === 0 && <div className="col-span-2 empty-state"><p className="empty-state-text">لا توجد نتائج</p></div>}
          </div>
        </div>
      )}

      {subject === "quran" && (
        <div className="panel p-6">
          <div className="panel-header"><h3 className="panel-title"><span className="panel-title-icon">📖</span> سور القرآن الكريم</h3></div>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">
            {QURAN_SURAHS.map((s) => (
              <div key={s.number} className="panel bg-canvas p-3 text-center">
                <span className="text-xs font-bold text-primary-dark">سورة</span>
                <p className="text-sm font-bold text-text-primary mt-1">{s.name}</p>
                <span className="text-2xs text-text-tertiary mt-1 block">{s.number}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {subject === "english" && (
        <div className="panel p-6">
          <div className="panel-header"><h3 className="panel-title"><span className="panel-title-icon">🔤</span> وحدات الإنجليزية</h3></div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {state.englishUnits.map((unit) => (
              <div key={unit.unitNumber} className="panel bg-canvas p-4">
                <h4 className="font-bold text-sm text-text-primary mb-3 flex items-center gap-2">
                  <AppIcon name="list_alt" size={16} className="text-primary" />
                  الوحدة {unit.unitNumber}
                </h4>
                <div className="space-y-1">
                  {unit.words.map((w, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs">
                      <span className="font-semibold text-primary-dark shrink-0 w-6">{i + 1}.</span>
                      <span className="font-semibold text-text-primary font-cause">{w.word}</span>
                      <span className="text-text-tertiary">— {w.definition}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
            {state.englishUnits.length === 0 && <div className="col-span-2 empty-state"><p className="empty-state-text">لا توجد وحدات مضافة</p></div>}
          </div>
        </div>
      )}

      <EditHadithModal hadith={editHadith} open={!!editHadith} onClose={() => setEditHadith(null)} />
    </div>
  );
}
